kiosk_mode:
  hide_assistant: true
title: Kiosk-mode hide assistant
views:
  - theme: Backend-selected
    title: Hide Search
    path: kiosk-mode-hide-assistant
    badges: []
    cards:
      - type: markdown
        content: This dashboard has the setting `hide_assistant` on `true`. The assistant icon is located at right of the header or inside the overflow menu (top-right corner) on small screens.
